[tool.poetry]
name = "chord-drs"
version = "1.0.0"
description = "An implementation of a data repository system (as per GA4GH's specs) for the Bento platform."
authors = [
    "David Lougheed <david.lougheed@mail.mcgill.ca>",
    "Sanjeev Lakhwani <sanjeev.lakhwani@mcgill.ca>",
]
license = "LGPL-3.0"
readme = "README.md"
packages = [{include = "chord_drs"}]
include = [
    "chord_drs/migrations/*",
    "chord_drs/migrations/**/*",
]

[tool.poetry.dependencies]
python = "^3.12"
aioboto3 = "^15.5.0"
bento-lib = {version = "^18.1.0", extras = ["fastapi"]}
alembic = "^1.16.0"
sqlalchemy = ">=2.0.29,<2.1"
python-multipart = "^0.0.20"
werkzeug = "~3.1.4"  # secure_filename
orjson = "^3.11.5"

[tool.poetry.group.dev.dependencies]
boto3-stubs = "~=1.40.61"
coverage = "^7.11.0"
moto = {version = "^5.1.15", extras = ["server"]}
pytest = "^7.4.4"  # 8.x not supported by pytest-lazy-fixture
pytest-asyncio = "~0.23.8"  # last version supporting pytest 7.x
pytest-cov = "^7.0.0"
pytest-dotenv = "^0.5.2"
responses = "^0.26.0"
tox = "^4.33.0"
debugpy = "^1.8.19"
pytest-lazy-fixture = "^0.6.3"
mypy = "~2.4.0"
httpx2 = "^2.13.1"
ruff = "^0.16.1"

[tool.poetry.scripts]
drs-ingest = "chord_drs.commands:ingest"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120
exclude = ["chord_drs/migrations"]

[tool.ruff.lint]
ignore = ["RUF022"]

# Custom pytest plugin to mock an S3 server
# pytest uses the "pytest11" entrypoint to lookup plugins
# https://docs.pytest.org/en/stable/how-to/writing_plugins.html
[tool.poetry.plugins."pytest11"]
s3_server_mock = 'tests.s3_server_mock'
