"""add public flag to DRS objects

Revision ID: dcd501398d46
Revises: e12d110bf938
Create Date: 2023-12-05 11:30:07.782924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcd501398d46'
down_revision = 'e12d110bf938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drs_bundle', sa.Column('public', sa.Boolean(), nullable=True))
    op.add_column('drs_object', sa.Column('public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drs_object', 'public')
    op.drop_column('drs_bundle', 'public')
    # ### end Alembic commands ###
