"""add Bento resource information

Revision ID: e12d110bf938
Revises: e696999dcee8
Create Date: 2023-07-13 11:02:01.897127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e12d110bf938'
down_revision = 'e696999dcee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drs_bundle', sa.Column('project_id', sa.String(length=64), nullable=True))
    op.add_column('drs_bundle', sa.Column('dataset_id', sa.String(length=64), nullable=True))
    op.add_column('drs_bundle', sa.Column('data_type', sa.String(length=24), nullable=True))
    op.add_column('drs_object', sa.Column('project_id', sa.String(length=64), nullable=True))
    op.add_column('drs_object', sa.Column('dataset_id', sa.String(length=64), nullable=True))
    op.add_column('drs_object', sa.Column('data_type', sa.String(length=24), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drs_object', 'data_type')
    op.drop_column('drs_object', 'dataset_id')
    op.drop_column('drs_object', 'project_id')
    op.drop_column('drs_bundle', 'data_type')
    op.drop_column('drs_bundle', 'dataset_id')
    op.drop_column('drs_bundle', 'project_id')
    # ### end Alembic commands ###
